import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { ArrowLeft, CheckCheckIcon, RotateCcwIcon } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@codexsun/ui/components/button";
import { WorkspacePage } from "@codexsun/ui/workspace/page";
import { WorkspaceStatusBadge } from "@codexsun/ui/workspace/status";
import { WorkspaceTableEmptyState, WorkspaceTableHeaderCell, WorkspaceTablePanel } from "@codexsun/ui/workspace/table";

const base=import.meta.env.VITE_DATA_BRIDGE_API_URL??"http://127.0.0.1:7090";
type QueryTable={sourceTable:string;targetTable:string;group:string;fields:Array<{sourceField:string;targetField:string}>;sourceQuery:string;targetQuery:string};
type TransformPlan={id:number;mappingPlanId:number;name:string;status:"draft"|"approved";tables:QueryTable[];createdAt:string;updatedAt:string;approvedAt?:string|null};
async function api<T>(path:string,init?:RequestInit){const options:RequestInit={...init};if(init?.body){const headers=new Headers(init.headers);headers.set("content-type","application/json");options.headers=headers;}const response=await fetch(`${base}${path}`,options);const body=await response.json() as {data?:T;message?:string};if(!response.ok||body.data===undefined)throw new Error(body.message??"Transform request failed.");return body.data;}
const listPlans=()=>api<TransformPlan[]>("/data-bridge/transform-plans");
const approve=(id:number,status:"draft"|"approved")=>api<TransformPlan>(`/data-bridge/transform-plans/${id}/approval`,{method:"PUT",body:JSON.stringify({status})});

export function TransformsWorkspace(){const client=useQueryClient();const[selected,setSelected]=useState<TransformPlan|null>(null);const query=useQuery({queryKey:["data-bridge","transform-plans"],queryFn:listPlans});const approval=useMutation({mutationFn:({id,status}:{id:number;status:"draft"|"approved"})=>approve(id,status),onSuccess:async(plan)=>{setSelected(plan);await client.invalidateQueries({queryKey:["data-bridge","transform-plans"]});toast.success(plan.status==="approved"?"Query plan approved":"Query plan returned to draft");},onError:error=>toast.error("Could not update approval",{description:error.message})});if(selected)return <TransformPlanPage plan={selected} pending={approval.isPending} onBack={()=>setSelected(null)} onStatus={(status)=>approval.mutate({id:selected.id,status})}/>;return <WorkspacePage title="Transforms" description="Review generated Source read queries and Target insert templates before approving the data-transfer plan."><WorkspaceTablePanel><table className="w-full text-sm"><thead className="bg-muted/50"><tr><WorkspaceTableHeaderCell>Reference</WorkspaceTableHeaderCell><WorkspaceTableHeaderCell>Transform plan</WorkspaceTableHeaderCell><WorkspaceTableHeaderCell>Field mapping</WorkspaceTableHeaderCell><WorkspaceTableHeaderCell>Tables</WorkspaceTableHeaderCell><WorkspaceTableHeaderCell>Status</WorkspaceTableHeaderCell></tr></thead><tbody>{(query.data??[]).map(plan=><tr className="border-b last:border-0" key={plan.id}><td className="px-4 py-2.5 font-mono text-xs">TR-{plan.id}</td><td className="px-4 py-2.5"><button className="font-medium hover:underline" onClick={()=>setSelected(plan)}>{plan.name}</button></td><td className="px-4 py-2.5 font-mono text-xs">FM-{plan.mappingPlanId}</td><td className="px-4 py-2.5">{plan.tables.length}</td><td className="px-4 py-2.5"><WorkspaceStatusBadge label={plan.status} tone={plan.status==="approved"?"success":"warning"}/></td></tr>)}</tbody></table>{!query.data?.length?<WorkspaceTableEmptyState>Save a Field Mapping plan to generate its Transform query plan.</WorkspaceTableEmptyState>:null}</WorkspaceTablePanel></WorkspacePage>}

function TransformPlanPage({plan,pending,onBack,onStatus}:{plan:TransformPlan;pending:boolean;onBack:()=>void;onStatus:(status:"draft"|"approved")=>void}){return <WorkspacePage title={`${plan.name} · TR-${plan.id}`} description="Visual Source-to-Target query plan. Approval makes this plan eligible for the next transfer stage." actions={<div className="flex gap-2"><Button variant="outline" onClick={onBack}><ArrowLeft className="size-4"/>Back</Button><Button disabled={pending} variant={plan.status==="approved"?"outline":"default"} onClick={()=>onStatus(plan.status==="approved"?"draft":"approved")}>{plan.status==="approved"?<RotateCcwIcon className="size-4"/>:<CheckCheckIcon className="size-4"/>}{plan.status==="approved"?"Return to draft":"Approve query plan"}</Button></div>}><div className="space-y-4">{plan.tables.map((table,index)=><section className="overflow-hidden rounded-md border bg-card" key={`${table.sourceTable}-${table.targetTable}`}><div className="grid border-b bg-muted/40 md:grid-cols-[3rem_1fr_auto_1fr]"><div className="flex items-center justify-center border-r font-mono text-xs">{index+1}</div><div className="border-r px-4 py-3"><span className="text-xs uppercase text-muted-foreground">Source</span><p className="font-mono font-semibold">{table.sourceTable}</p></div><div className="flex items-center px-4 text-primary">→</div><div className="px-4 py-3"><span className="text-xs uppercase text-muted-foreground">Target</span><p className="font-mono font-semibold">{table.targetTable}</p></div></div><div className="grid lg:grid-cols-2"><QueryBlock label="Source read query" query={table.sourceQuery}/><QueryBlock label="Target insert template" query={table.targetQuery}/></div><div className="border-t px-4 py-3 text-xs text-muted-foreground">{table.fields.length} mapped fields{table.group?` · Group: ${table.group}`:""}</div></section>)}</div></WorkspacePage>}
function QueryBlock({label,query}:{label:string;query:string}){return <div className="min-w-0 border-b p-4 last:border-b-0 lg:border-b-0 lg:border-r lg:last:border-r-0"><p className="mb-2 text-xs font-semibold uppercase text-muted-foreground">{label}</p><pre className="overflow-x-auto whitespace-pre-wrap break-words rounded-md border bg-slate-950 p-3 font-mono text-xs leading-6 text-emerald-300">{query}</pre></div>}
