import { useMemo, useState } from "react";
declare namespace React { type ReactNode = import("react").ReactNode; }
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Check, Circle, ListChecks, Pencil, Plus, RefreshCw, Trash2, X } from "lucide-react";
import { toast } from "sonner";
import { Button, Input, Textarea } from "@codexsun/ui";
import { WorkspacePage } from "@codexsun/ui/workspace/page";
import { WorkspaceSelect } from "@codexsun/ui/workspace/select";
import { WorkspaceStatusBadge } from "@codexsun/ui/workspace/status";
import { createTodo, deleteTodo, listTodos, setTodoStatus, updateTodo } from "./task-manager.services";
import type { Todo, TodoInput, TodoPriority, TodoStatus } from "./task-manager.types";

const statusOptions = [{ label: "Open", value: "open" }, { label: "In progress", value: "in-progress" }, { label: "Completed", value: "completed" }];
const priorityOptions = [{ label: "Low", value: "low" }, { label: "Medium", value: "medium" }, { label: "High", value: "high" }];
export function TaskManagerWorkspace() {
  const client = useQueryClient(); const query = useQuery({ queryKey: ["task-manager", "todos"], queryFn: listTodos }); const [editing, setEditing] = useState<Todo | null>(null); const [search, setSearch] = useState("");
  const refresh = () => client.invalidateQueries({ queryKey: ["task-manager", "todos"] });
  const save = useMutation({ mutationFn: (input: TodoInput) => editing ? updateTodo(editing.id, input) : createTodo(input), onSuccess: async todo => { await refresh(); setEditing(null); toast.success("Todo saved", { description: todo.title }); } });
  const status = useMutation({ mutationFn: ({ id, value }: { id: string; value: TodoStatus }) => setTodoStatus(id, value), onSuccess: refresh });
  const remove = useMutation({ mutationFn: deleteTodo, onSuccess: refresh }); const todos = useMemo(() => (query.data ?? []).filter(todo => `${todo.title} ${todo.description} ${todo.priority} ${todo.status}`.toLowerCase().includes(search.toLowerCase())), [query.data, search]);
  const open = todos.filter(todo => todo.status !== "completed").length; const completed = todos.filter(todo => todo.status === "completed").length;
  return <WorkspacePage title="Task Manager" description="Plan and complete tenant-owned Todos in a lightweight workspace." actions={<div className="flex flex-wrap gap-2"><Button variant="outline" onClick={() => void query.refetch()}><RefreshCw className="size-4" />Refresh</Button><Button onClick={() => setEditing({ id: "", title: "", description: "", status: "open", priority: "medium", dueDate: "", createdAt: "", updatedAt: "" })}><Plus className="size-4" />New Todo</Button></div>}><div className="grid gap-4 md:grid-cols-3"><Metric label="Total Todos" value={todos.length} icon={<ListChecks className="size-4" />} /><Metric label="Open" value={open} icon={<Circle className="size-4" />} /><Metric label="Completed" value={completed} icon={<Check className="size-4" />} /></div><div className="mt-4 rounded-md border bg-card p-4"><Input value={search} onChange={event => setSearch(event.target.value)} placeholder="Search Todos" /></div>{editing ? <TodoForm value={editing} saving={save.isPending} onCancel={() => setEditing(null)} onSave={value => save.mutate(value)} /> : null}<div className="mt-4 overflow-x-auto rounded-md border bg-card shadow-sm"><table className="w-full min-w-[760px] text-sm"><thead className="border-b bg-muted/50"><tr><th className="px-4 py-3 text-left">Todo</th><th className="px-4 py-3 text-left">Priority</th><th className="px-4 py-3 text-left">Due date</th><th className="px-4 py-3 text-left">Status</th><th className="px-4 py-3 text-right">Action</th></tr></thead><tbody>{todos.map(todo => <tr className="border-b last:border-0" key={todo.id}><td className="px-4 py-3"><div className="font-medium">{todo.title}</div>{todo.description ? <div className="mt-1 text-xs text-muted-foreground">{todo.description}</div> : null}</td><td className="px-4 py-3 capitalize">{todo.priority}</td><td className="px-4 py-3">{todo.dueDate || "-"}</td><td className="px-4 py-3"><WorkspaceStatusBadge label={todo.status} tone={todo.status === "completed" ? "success" : todo.status === "in-progress" ? "info" : "warning"} /></td><td className="px-4 py-3"><div className="flex justify-end gap-1"><Button size="icon" variant="outline" title="Edit" onClick={() => setEditing(todo)}><Pencil className="size-4" /></Button>{todo.status !== "completed" ? <Button size="icon" variant="outline" title="Complete" onClick={() => status.mutate({ id: todo.id, value: "completed" })}><Check className="size-4" /></Button> : null}<Button size="icon" variant="outline" title="Delete" onClick={() => remove.mutate(todo.id)}><Trash2 className="size-4" /></Button></div></td></tr>)}</tbody></table>{!todos.length ? <p className="p-10 text-center text-muted-foreground">No Todos found.</p> : null}</div></WorkspacePage>;
}
function TodoForm({ value, saving, onCancel, onSave }: { value: Todo; saving: boolean; onCancel: () => void; onSave: (value: TodoInput) => void }) { const [form, setForm] = useState<TodoInput>({ title: value.title, description: value.description, status: value.status, priority: value.priority, dueDate: value.dueDate }); const patch = (key: keyof TodoInput, next: string) => setForm(current => ({ ...current, [key]: next })); return <form className="mt-4 rounded-md border bg-card p-5 shadow-sm" onSubmit={event => { event.preventDefault(); if (!form.title.trim()) return; onSave(form); }}><div className="grid gap-4 md:grid-cols-2"><label className="grid gap-2 text-sm font-medium"><span>Todo title *</span><Input required value={form.title} onChange={event => patch("title", event.target.value)} /></label><label className="grid gap-2 text-sm font-medium"><span>Due date</span><Input type="date" value={form.dueDate ?? ""} onChange={event => patch("dueDate", event.target.value)} /></label><label className="grid gap-2 text-sm font-medium"><span>Status</span><WorkspaceSelect options={statusOptions} value={String(form.status ?? "open")} onValueChange={value => patch("status", value)} /></label><label className="grid gap-2 text-sm font-medium"><span>Priority</span><WorkspaceSelect options={priorityOptions} value={String(form.priority ?? "medium")} onValueChange={value => patch("priority", value)} /></label><label className="grid gap-2 text-sm font-medium md:col-span-2"><span>Description</span><Textarea rows={3} value={form.description ?? ""} onChange={event => patch("description", event.target.value)} /></label></div><div className="mt-4 flex gap-2"><Button disabled={saving} type="submit">Save Todo</Button><Button type="button" variant="outline" onClick={onCancel}><X className="size-4" />Cancel</Button></div></form>; }
function Metric({ icon, label, value }: { icon: React.ReactNode; label: string; value: number }) { return <div className="rounded-md border bg-card p-4 shadow-sm"><div className="flex items-center justify-between text-sm text-muted-foreground">{label}{icon}</div><div className="mt-2 text-2xl font-semibold">{value}</div></div>; }
