ARG FILEBROWSER_BASE_IMAGE=filebrowser/filebrowser:v2.63.5
FROM ${FILEBROWSER_BASE_IMAGE}

ARG CODEXSUN_VERSION=1.0.33
LABEL org.opencontainers.image.title="CODEXSUN Media" \
      org.opencontainers.image.version="$CODEXSUN_VERSION"
