import { useState } from "react";
import { ArrowLeft, Download } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@codexsun/ui/components/button";
import { WorkspacePage } from "@codexsun/ui/workspace/page";
import { WorkspaceStatusBadge } from "@codexsun/ui/workspace/status";
import {
  ExceptionResolutionForm,
  ReconciliationExceptionForm,
  ReconciliationGenerateForm,
  ReconciliationSignOffForm
} from "./reconciliation-audit.form";
import {
  useCompletedExecutionOptions,
  useReconciliationActions,
  useReconciliationReports
} from "./reconciliation-audit.hooks";
import { ReconciliationAuditList } from "./reconciliation-audit.list";
import type { ReconciliationReport } from "./reconciliation-audit.types";
export function ReconciliationAuditWorkspace() {
  const reports = useReconciliationReports();
  const runs = useCompletedExecutionOptions();
  const actions = useReconciliationActions();
  const [selectedId, setSelectedId] = useState<number | null>(null);
  const selected = (reports.data ?? []).find((report) => report.id === selectedId) ?? null;
  const save = (promise: Promise<ReconciliationReport>, message: string) =>
    promise
      .then((report) => {
        setSelectedId(report.id);
        toast.success(message);
      })
      .catch((error: Error) => toast.error(message, { description: error.message }));
  const download = async (id: number) => {
    try {
      const data = await actions.exportAudit.mutateAsync(id);
      const url = URL.createObjectURL(
        new Blob([JSON.stringify(data, null, 2)], { type: "application/json" })
      );
      const anchor = document.createElement("a");
      anchor.href = url;
      anchor.download = `data-bridge-reconciliation-${id}.json`;
      anchor.click();
      URL.revokeObjectURL(url);
    } catch (error) {
      toast.error("Could not export audit evidence", {
        description: error instanceof Error ? error.message : "Unknown error"
      });
    }
  };
  if (selected)
    return (
      <WorkspacePage
        title={`${selected.name} · RC-${selected.id}`}
        description={`Execution EX-${selected.executionRunId} · generated by ${selected.generatedBy}`}
        actions={
          <div className="flex gap-2">
            <Button variant="outline" onClick={() => setSelectedId(null)}>
              <ArrowLeft className="size-4" />
              Back
            </Button>
            <Button variant="outline" onClick={() => download(selected.id)}>
              <Download className="size-4" />
              Audit export
            </Button>
          </div>
        }
      >
        <div className="space-y-4">
          <div className="grid gap-3 rounded-md border bg-card p-4 sm:grid-cols-3">
            <Metric
              label="Status"
              value={
                <WorkspaceStatusBadge
                  label={selected.status}
                  tone={
                    selected.status === "signed_off"
                      ? "success"
                      : selected.status === "needs_attention"
                        ? "danger"
                        : "warning"
                  }
                />
              }
            />
            <Metric
              label="Verified rows"
              value={selected.tables.reduce((sum, table) => sum + table.verifiedRows, 0)}
            />
            <Metric
              label="Open exceptions"
              value={selected.exceptions.filter((item) => item.status === "open").length}
            />
          </div>
          <div className="grid gap-3 lg:grid-cols-2">
            {selected.tables.map((table) => (
              <section key={table.targetTable} className="rounded-md border bg-card p-4">
                <div className="flex justify-between">
                  <p className="font-mono font-semibold">
                    {table.sourceTable} → {table.targetTable}
                  </p>
                  <WorkspaceStatusBadge
                    label={table.missingRows || table.mismatchedRows ? "exception" : "matched"}
                    tone={table.missingRows || table.mismatchedRows ? "danger" : "success"}
                  />
                </div>
                <p className="mt-3 text-sm">
                  Verified {table.verifiedRows} / {table.insertedRows + table.overriddenRows}
                </p>
                <p className="mt-1 text-xs text-muted-foreground">
                  Inserted {table.insertedRows} · Overridden {table.overriddenRows} · Rejected{" "}
                  {table.rejectedRows} · Missing {table.missingRows} · Mismatch{" "}
                  {table.mismatchedRows}
                </p>
                <p className="mt-2 truncate font-mono text-xs text-muted-foreground">
                  Source {table.sourceHash}
                </p>
                <p className="truncate font-mono text-xs text-muted-foreground">
                  Target {table.targetHash}
                </p>
              </section>
            ))}
          </div>
          <div className="grid gap-3 lg:grid-cols-2">
            {selected.exceptions.map((item) => (
              <section key={item.id} className="space-y-2 rounded-md border bg-card p-4">
                <div className="flex justify-between">
                  <p className="font-semibold">
                    {item.id} · {item.table}
                  </p>
                  <WorkspaceStatusBadge
                    label={item.status}
                    tone={item.status === "resolved" ? "success" : "danger"}
                  />
                </div>
                <p className="text-sm">{item.details}</p>
                {item.resolution ? (
                  <p className="text-sm text-muted-foreground">Resolution: {item.resolution}</p>
                ) : null}
                {item.status === "open" ? (
                  <ExceptionResolutionForm
                    item={item}
                    pending={actions.resolve.isPending}
                    error={actions.resolve.error?.message}
                    onSubmit={(input) =>
                      save(
                        actions.resolve.mutateAsync({
                          id: selected.id,
                          exceptionId: item.id,
                          input
                        }),
                        "Exception resolved"
                      )
                    }
                  />
                ) : null}
              </section>
            ))}
          </div>
          {selected.status !== "signed_off" ? (
            <div className="grid gap-4 lg:grid-cols-2">
              <ReconciliationExceptionForm
                tables={selected.tables.map((table) => table.targetTable)}
                pending={actions.addException.isPending}
                error={actions.addException.error?.message}
                onSubmit={(input) =>
                  save(
                    actions.addException.mutateAsync({ id: selected.id, input }),
                    "Exception recorded"
                  )
                }
              />
              {selected.status === "pending_signoff" ? (
                <ReconciliationSignOffForm
                  pending={actions.sign.isPending}
                  error={actions.sign.error?.message}
                  onSubmit={(input) =>
                    save(
                      actions.sign.mutateAsync({ id: selected.id, input }),
                      "Client sign-off recorded"
                    )
                  }
                />
              ) : (
                <section className="rounded-md border bg-muted/30 p-4 text-sm text-muted-foreground">
                  Resolve every open exception before client sign-off.
                </section>
              )}
            </div>
          ) : (
            <section className="rounded-md border bg-card p-4">
              <p className="font-semibold">Signed by {selected.signOff?.signedBy}</p>
              <p className="text-sm text-muted-foreground">
                {selected.signOff?.clientName} · {selected.signOff?.clientReference} ·{" "}
                {selected.signOff?.signedAt}
              </p>
            </section>
          )}
        </div>
      </WorkspacePage>
    );
  return (
    <WorkspacePage
      title="Reconciliation & Audit"
      description="Verify transferred records against Target hashes, resolve exceptions, capture client sign-off, and export immutable evidence."
    >
      <div className="space-y-4">
        <ReconciliationGenerateForm
          runs={runs.data ?? []}
          pending={actions.generate.isPending}
          error={actions.generate.error?.message}
          onSubmit={(input) =>
            save(actions.generate.mutateAsync(input), "Reconciliation report generated")
          }
        />
        <ReconciliationAuditList
          records={reports.data ?? []}
          loading={reports.isLoading}
          onView={(report) => setSelectedId(report.id)}
        />
      </div>
    </WorkspacePage>
  );
}
function Metric({ label, value }: { label: string; value: React.ReactNode }) {
  return (
    <div>
      <p className="text-xs uppercase text-muted-foreground">{label}</p>
      <div className="mt-1 font-semibold">{value}</div>
    </div>
  );
}
