ARG FILEBROWSER_BASE_IMAGE=filebrowser/filebrowser:v2.63.5
FROM ${FILEBROWSER_BASE_IMAGE}

ARG CODEXSUN_VERSION=1.0.32
ARG STORAGE_ROLE=files
LABEL org.opencontainers.image.title="CODEXSUN Storage - ${STORAGE_ROLE}" \
      org.opencontainers.image.version="$CODEXSUN_VERSION"
