import { randomUUID } from "node:crypto";
import { getBillingDatabase } from "../../database/billing-database.js";
import type { Payment, PaymentInput, PaymentStatus } from "./payment.types.js";

export class PaymentRepository {
  async list(databaseName: string) { const db = await getBillingDatabase(databaseName) as any; const rows = await db.selectFrom("billing_payments").selectAll().orderBy("payment_date", "desc").orderBy("payment_number", "desc").execute(); return rows.map(toPayment); }
  async get(databaseName: string, id: string) { const db = await getBillingDatabase(databaseName) as any; const row = await db.selectFrom("billing_payments").selectAll().where("id", "=", id).executeTakeFirst(); return row ? toPayment(row) : null; }
  async findByNumber(databaseName: string, number: string) { const db = await getBillingDatabase(databaseName) as any; const row = await db.selectFrom("billing_payments").selectAll().where("payment_number", "=", number).executeTakeFirst(); return row ? toPayment(row) : null; }
  async create(databaseName: string, input: PaymentInput) { const record = makePayment(input); const db = await getBillingDatabase(databaseName) as any; await db.insertInto("billing_payments").values(toRow(record)).execute(); return record; }
  async update(databaseName: string, id: string, input: PaymentInput) { const db = await getBillingDatabase(databaseName) as any; const current = await db.selectFrom("billing_payments").select(["created_at"]).where("id", "=", id).executeTakeFirst(); if (!current) return null; const record = makePayment(input, id, current.created_at); await db.updateTable("billing_payments").set(toRow(record)).where("id", "=", id).execute(); return record; }
  async setStatus(databaseName: string, id: string, status: PaymentStatus) { const db = await getBillingDatabase(databaseName) as any; await db.updateTable("billing_payments").set({ status, updated_at: new Date().toISOString() }).where("id", "=", id).execute(); return this.get(databaseName, id); }
  async delete(databaseName: string, id: string) { const record = await this.get(databaseName, id); if (!record) return null; const db = await getBillingDatabase(databaseName) as any; await db.deleteFrom("billing_payments").where("id", "=", id).execute(); return record; }
}

function makePayment(input: PaymentInput, id = `payment-${randomUUID().slice(0, 8)}`, createdAt = new Date().toISOString()): Payment {
  const allocations = input.allocations ?? [];
  const allocatedAmount = round(allocations.reduce((sum, item) => sum + Number(item.allocatedAmount || 0), 0));
  const amount = Number(input.amount || 0);
  const totalAmount = round(amount + Number(input.tdsAmount || 0) - Number(input.discountAmount || 0) + Number(input.roundOff || 0));
  return { id, paymentNumber: String(input.paymentNumber ?? ""), paymentDate: input.paymentDate, partyName: input.partyName.trim(), partyId: String(input.partyId ?? ""), partyType: String(input.partyType ?? "supplier"), paymentMode: String(input.paymentMode ?? "cash"), bankAccount: String(input.bankAccount ?? ""), referenceNo: String(input.referenceNo ?? ""), referenceDate: String(input.referenceDate ?? ""), amount, tdsAmount: Number(input.tdsAmount || 0), discountAmount: Number(input.discountAmount || 0), roundOff: Number(input.roundOff || 0), totalAmount, allocatedAmount, unallocatedAmount: round(totalAmount - allocatedAmount), status: (input.status ?? "draft") as PaymentStatus, notes: String(input.notes ?? ""), allocations, createdAt, updatedAt: new Date().toISOString() };
}
function toPayment(row: any): Payment { return { id: row.id, paymentNumber: row.payment_number, paymentDate: row.payment_date, partyName: row.party_name, partyId: row.party_id ?? "", partyType: row.party_type, paymentMode: row.payment_mode, bankAccount: row.bank_account ?? "", referenceNo: row.reference_no ?? "", referenceDate: row.reference_date ?? "", amount: Number(row.amount), tdsAmount: Number(row.tds_amount), discountAmount: Number(row.discount_amount), roundOff: Number(row.round_off), totalAmount: Number(row.total_amount), allocatedAmount: Number(row.allocated_amount), unallocatedAmount: Number(row.unallocated_amount), status: row.status, notes: row.notes ?? "", allocations: parse(row.allocations_json), createdAt: row.created_at, updatedAt: row.updated_at }; }
function toRow(record: Payment) { return { id: record.id, payment_number: record.paymentNumber, payment_date: record.paymentDate, party_name: record.partyName, party_id: record.partyId || null, party_type: record.partyType, payment_mode: record.paymentMode, bank_account: record.bankAccount || null, reference_no: record.referenceNo || null, reference_date: record.referenceDate || null, amount: record.amount, tds_amount: record.tdsAmount, discount_amount: record.discountAmount, round_off: record.roundOff, total_amount: record.totalAmount, allocated_amount: record.allocatedAmount, unallocated_amount: record.unallocatedAmount, status: record.status, notes: record.notes, allocations_json: JSON.stringify(record.allocations), created_at: record.createdAt, updated_at: record.updatedAt }; }
function parse(value: string | null) { try { const result = JSON.parse(value ?? "[]"); return Array.isArray(result) ? result : []; } catch { return []; } }
function round(value: number) { return Math.round(value * 100) / 100; }
