import type { CommonMasterDefinition } from "../../foundation/common-master.types.js";

const bankNames = [
  "-",
  "State Bank of India",
  "Bank of Baroda",
  "Bank of India",
  "Bank of Maharashtra",
  "Canara Bank",
  "Central Bank of India",
  "Indian Bank",
  "Indian Overseas Bank",
  "Punjab & Sind Bank",
  "Punjab National Bank",
  "UCO Bank",
  "Union Bank of India",
  "Axis Bank Limited",
  "Bandhan Bank Limited",
  "CSB Bank Limited",
  "City Union Bank Limited",
  "DCB Bank Limited",
  "Dhanlaxmi Bank Limited",
  "Federal Bank Limited",
  "HDFC Bank Limited",
  "ICICI Bank Limited",
  "IndusInd Bank Limited",
  "IDFC FIRST Bank Limited",
  "Jammu & Kashmir Bank Limited",
  "Karnataka Bank Limited",
  "Karur Vysya Bank Limited",
  "Kotak Mahindra Bank Limited",
  "Nainital Bank Limited",
  "RBL Bank Limited",
  "South Indian Bank Limited",
  "Tamilnad Mercantile Bank Limited",
  "YES Bank Limited",
  "IDBI Bank Limited",
  "Coastal Local Area Bank Limited",
  "Krishna Bhima Samruddhi Local Area Bank Limited",
  "AU Small Finance Bank Limited",
  "Capital Small Finance Bank Limited",
  "Equitas Small Finance Bank Limited",
  "ESAF Small Finance Bank Limited",
  "Suryoday Small Finance Bank Limited",
  "Ujjivan Small Finance Bank Limited",
  "Utkarsh Small Finance Bank Limited",
  "slice Small Finance Bank Limited",
  "Jana Small Finance Bank Limited",
  "Shivalik Small Finance Bank Limited",
  "Unity Small Finance Bank Limited",
  "India Post Payments Bank Limited",
  "Fino Payments Bank Limited",
  "Airtel Payments Bank Limited",
  "Jio Payments Bank Limited",
  "NSDL Payments Bank Limited",
  "Andhra Pradesh Grameena Bank",
  "Assam Gramin Bank",
  "Arunachal Pradesh Rural Bank",
  "Bihar Gramin Bank",
  "Chhattisgarh Gramin Bank",
  "Gujarat Gramin Bank",
  "Haryana Gramin Bank",
  "Himachal Pradesh Gramin Bank",
  "Jharkhand Gramin Bank",
  "Jammu and Kashmir Grameen Bank",
  "Karnataka Grameena Bank",
  "Kerala Grameena Bank",
  "Maharashtra Gramin Bank",
  "Madhya Pradesh Gramin Bank",
  "Manipur Rural Bank",
  "Meghalaya Rural Bank",
  "Mizoram Rural Bank",
  "Nagaland Rural Bank",
  "Odisha Grameen Bank",
  "Punjab Gramin Bank",
  "Puducherry Grama Bank",
  "Rajasthan Gramin Bank",
  "Tamil Nadu Grama Bank",
  "Telangana Grameena Bank",
  "Tripura Gramin Bank",
  "Uttar Pradesh Gramin Bank",
  "Uttarakhand Gramin Bank",
  "West Bengal Gramin Bank",
  "AB Bank PLC",
  "American Express Banking Corporation",
  "Australia and New Zealand Banking Group Limited",
  "Barclays Bank PLC",
  "Bank of America, National Association",
  "Bank of Bahrain and Kuwait B.S.C.",
  "Bank of Ceylon",
  "Bank of China Limited",
  "Bank of Nova Scotia",
  "BNP Paribas",
  "Citibank N.A.",
  "Cooperatieve Rabobank U.A.",
  "Credit Agricole Corporate and Investment Bank",
  "CTBC Bank Co., Limited",
  "DBS Bank India Limited",
  "Deutsche Bank A.G.",
  "Doha Bank Q.P.S.C.",
  "Emirates NBD Bank P.J.S.C.",
  "First Abu Dhabi Bank PJSC",
  "FirstRand Bank Limited",
  "Hong Kong and Shanghai Banking Corporation Limited",
  "Industrial and Commercial Bank of China Limited",
  "Industrial Bank of Korea",
  "J.P. Morgan Chase Bank N.A.",
  "JSC VTB Bank",
  "KEB Hana Bank",
  "Kookmin Bank",
  "Mashreqbank P.S.C.",
  "Mizuho Bank Limited",
  "MUFG Bank, Limited",
  "NatWest Markets PLC",
  "NongHyup Bank",
  "PT Bank Maybank Indonesia TBK",
  "Qatar National Bank Q.P.S.C.",
  "Sberbank",
  "SBM Bank (India) Limited",
  "Shinhan Bank",
  "Societe Generale",
  "Sonali Bank PLC",
  "Standard Chartered Bank",
  "Sumitomo Mitsui Banking Corporation",
  "United Overseas Bank Limited",
  "UBS AG",
  "Woori Bank",
  "Andaman and Nicobar State Co-operative Bank Limited",
  "Andhra Pradesh State Co-operative Bank Limited",
  "Arunachal Pradesh State Co-operative Apex Bank Limited",
  "Assam Co-operative Apex Bank Limited",
  "Bihar State Co-operative Bank Limited",
  "Chandigarh State Co-operative Bank Limited",
  "Chhattisgarh Rajya Sahakari Bank Maryadit",
  "Delhi State Co-operative Bank Limited",
  "Goa State Co-operative Bank Limited",
  "Gujarat State Co-operative Bank Limited",
  "Haryana State Co-operative Apex Bank Limited",
  "Himachal Pradesh State Co-operative Bank Limited",
  "Jammu and Kashmir State Co-operative Bank Limited",
  "Jharkhand State Co-operative Bank Limited",
  "Karnataka State Co-operative Apex Bank Limited",
  "Kerala State Co-operative Bank Limited",
  "Madhya Pradesh Rajya Sahakari Bank Maryadit",
  "Maharashtra State Co-operative Bank Limited",
  "Manipur State Co-operative Bank Limited",
  "Meghalaya Co-operative Apex Bank Limited",
  "Mizoram Co-operative Apex Bank Limited",
  "Nagaland State Co-operative Bank Limited",
  "Odisha State Co-operative Bank Limited",
  "Puducherry State Co-operative Bank Limited",
  "Punjab State Co-operative Bank Limited",
  "Rajasthan State Co-operative Bank Limited",
  "Sikkim State Co-operative Bank Limited",
  "Tamil Nadu State Apex Co-operative Bank Limited",
  "Telangana State Cooperative Apex Bank Limited",
  "Tripura State Co-operative Bank Limited",
  "Uttar Pradesh Co-operative Bank Limited",
  "Uttarakhand State Co-operative Bank Limited",
  "West Bengal State Co-operative Bank Limited",
  "Daman and Diu State Co-operative Bank Limited"
] as const;

export const bankNamesDefinition: CommonMasterDefinition = {
  "allowGlobalMutations": true,
  "fields": [
    {
      "key": "name",
      "column": "name",
      "label": "Name",
      "type": "string",
      "required": true
    }
  ],
  "group": "contacts",
  "key": "bankNames",
  "label": "Bank Names",
  "path": "/core/common/contacts/bank-names",
  "seeds": bankNames.map((name) => ({ name })),
  "tableName": "core_common_bank_names"
};
